site:
  title: Dfinity 日本語ドキュメント
  url: https://nifty-beaver-611cb8.netlify.app
  start_page: docs:introduction:welcome.adoc
content:
  sources:
    - url: https://github.com/Japan-DfinityInfoHub/docs
      branches: HEAD
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
